### ISSUE TITLE
Can't write material - Key error subsurface radius

### ISSUE THREAD

**Issue by Vidyut** [makehumancommunity/mpfb2#131]
I've customised a character. When I try to write the material, the first time I click save as, it tries to save the blend file. If I click save as mhmat anyway, the file selector closes, but nothing is saved. I can't save to library either.

There is an error that says:
`Python: Traceback (most recent call last):
  File "/home/vidyut/.config/blender/3.6/scripts/addons/mpfb/ui/makeskin/operators/writematerial.py", line 55, in execute
    material.populate_from_object(blender_object)
  File "/home/vidyut/.config/blender/3.6/scripts/addons/mpfb/entities/material/makeskinmaterial.py", line 151, in populate_from_object
    radius = socket_values["Subsurface Radius"]
KeyError: 'Subsurface Radius'
bpy.ops.mpfb.write_makeskin_material(filepath="/home/vidyut/ART/BLENDER/projects/ax-defined.mhmat")
`

**Comment by joepal1976** [comment]
Thanks. Seems like I broke something when I updated makeskin recently. I'll look into it.

**Comment by joepal1976** [comment]
I've pushed a fix now. It is available from git or in tomorrow's nightly build. Can you check if this solves the problem?

**Comment by Vidyut** [comment]
I still have the problem. Not sure if it is because I upgraded wrong or something. Been caught up with stuff and did it in a hurry, but no change in the problem.

**Comment by joepal1976** [comment]
I noticed that the traceback you provided earlier looked as if it came from an older version, as the line numbers did not match what is currently in the source code.

Can you try upgrading again and provide a new traceback if the problem persist?

**Comment by joepal1976** [comment]
@Vidyut : Is this issue still relevant?

**Comment by joepal1976** [comment]
Assuming this is no longer an issue.
