### ISSUE TITLE
Blender 4: Can't apply skin material, 'ShaderNodeTree' object has no attribute 'inputs'

### ISSUE THREAD

**Issue by HaasJona** [makehumancommunity/mpfb2#158]
**Describe the bug**
Using Blender 4.01 and the latest Blender 4 alpha build of this plug-in http://files.makehumancommunity.org/plugins/mpfb2-blender4-20231118.zip I get an python error when trying to apply a skin to a newly created human.

**Screenshots / logs**
```
bpy.ops.mpfb.load_library_skin(filepath="/home/jh/.config/blender/4.0/mpfb/data/skins/young_caucasian_male2/young_caucasian_male2.mhmat")
Python: Traceback (most recent call last):
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/ui/assetlibrary/operators/loadlibraryskin.py", line 38, in execute
    HumanService.set_character_skin(self.filepath, basemesh, bodyproxy=bodyproxy, skin_type=skin_type, material_instances=material_instances)
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/services/humanservice.py", line 591, in set_character_skin
    enhanced_material.apply_node_tree(blender_material)
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/entities/material/enhancedskinmaterial.py", line 99, in apply_node_tree
    NodeService.apply_node_tree_from_dict(blender_material.node_tree, node_tree_dict, True)
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/services/nodeservice.py", line 571, in apply_node_tree_from_dict
    else:
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/services/nodeservice.py", line 540, in _ensure_group_interfaces_exist
    
AttributeError: 'ShaderNodeTree' object has no attribute 'inputs'
```

This might be relevant: https://blender.stackexchange.com/questions/302590/attributeerror-shadernodetree-object-has-no-attribute-active-output

**Platform and versions**
 - OS: Fedora Workstation 39
 - Version of Blender: 4.0.1 installed with Steam
 - Version of MPFB: mpfb2-blender4-20231118

**Comment by joepal1976** [comment]
Thanks. Yes, materials is the main thing being shaky in the blender4 branch atm. I'm working on it.

Which skin model have you set as default? This can be seen in the dropdown "skin type" in the panel "apply assets" -> "library settings" -> "skin"

**Comment by joepal1976** [comment]
I've pushed fixes I think solve the problem now. I'm on the release candidate for blender4 though, and can't download 4.0.1 since blender is under DDOS attack. 

Maybe you can test if today's nightly build solves the problem?

**Comment by HaasJona** [comment]
The problem still seems to happen in http://files.makehumancommunity.org/plugins/mpfb2-blender4-20231122.zip

Exception with skin setting Enhanced + SSS (v1):
```
Error: Python: Traceback (most recent call last):
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/ui/assetlibrary/operators/loadlibraryskin.py", line 38, in execute
    HumanService.set_character_skin(self.filepath, basemesh, bodyproxy=bodyproxy, skin_type=skin_type, material_instances=material_instances)
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/services/humanservice.py", line 591, in set_character_skin
    enhanced_material.apply_node_tree(blender_material)
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/entities/material/enhancedskinmaterial.py", line 99, in apply_node_tree
    NodeService.apply_node_tree_from_dict(blender_material.node_tree, node_tree_dict, True)
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/services/nodeservice.py", line 571, in apply_node_tree_from_dict
    socket = NodeService._create_socket(node_tree, output_name, group["outputs"][output_name], in_out="OUTPUT")
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/services/nodeservice.py", line 540, in _ensure_group_interfaces_exist
    if isinstance(node, NodeGroupOutput):
AttributeError: 'ShaderNodeTree' object has no attribute 'inputs'
```

Exception with miltilayered (v2):
```
Error: Python: Traceback (most recent call last):
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/ui/assetlibrary/operators/loadlibraryskin.py", line 38, in execute
    HumanService.set_character_skin(self.filepath, basemesh, bodyproxy=bodyproxy, skin_type=skin_type, material_instances=material_instances)
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/services/humanservice.py", line 568, in set_character_skin
    blender_material = MaterialService.create_v2_skin_material(name, basemesh, mhmat_file)
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/services/materialservice.py", line 213, in create_v2_skin_material
    NodeWrapperSkin.create_instance(node_tree)
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/entities/nodemodel/v2/materials/abstractmaterialwrapper.py", line 22, in create_instance
    self.pre_create_instance(node_tree)
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/entities/nodemodel/v2/materials/abstractmaterialwrapper.py", line 40, in pre_create_instance
    self.setup_group_nodes(node_tree, nodes)
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/entities/nodemodel/v2/materials/nodewrapperskin.py", line 483, in setup_group_nodes
    node("MpfbBody", "bodygroup", label="Body Settings", attribute_values={"color": [0.608, 0.608, 0.608], "height": 100.0, "location": [711.826, 2404.9126], "use_custom_color": False, "width": 315.4109}, input_socket_values={"ColorVariationStrength": 0.25, "ColorVariationScaleMultiplier": 35.0})
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/entities/nodemodel/v2/materials/nodewrapperskin.py", line 474, in node
    nodes[name] = AbstractMaterialWrapper.node(node_class_name, node_tree, name, label=label, input_socket_values=input_socket_values, attribute_values=attribute_values, output_socket_values=output_socket_values)
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/entities/nodemodel/v2/composites/abstractgroupwrapper.py", line 117, in node
    raise ValueError('No such node or group: ' + node_class_name)
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/entities/nodemodel/v2/primitives/abstractnodewrapper.py", line 229, in create_instance
    value_class = socket_def["class"]
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/entities/nodemodel/v2/composites/abstractgroupwrapper.py", line 227, in pre_create_instance
    max_value = input_def["max_value"]
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/entities/nodemodel/v2/composites/abstractgroupwrapper.py", line 216, in create_node_tree
    output = NodeService.find_first_node_by_type_name(node_tree, "NodeGroupOutput")
  File "/home/jh/.config/blender/4.0/scripts/addons/mpfb/entities/nodemodel/v2/composites/abstractgroupwrapper.py", line 137, in add_input_socket
    # TODO: This is a blender 4 workaround. Ideally we should stop using FloatFactor in the definition instead.
AttributeError: 'ShaderNodeTree' object has no attribute 'inputs'
```

**Comment by joepal1976** [comment]
Thank you for the detailed information you provide. 

The stack traces look very strange though. The final line in each stack trace list a line which does not contain the operation that is then reported as causing the exception. For example, in the second stack trace, the final line is 

    # TODO: This is a blender 4 workaround. Ideally we should stop using FloatFactor in the definition instead.

Obviously, a comment is not able to cause an AttributeError. 

Further, I've downloaded the zip file and searched through the relevant methods. As far as I can see, the "inputs" property is never read on a node tree in these.

Finally I have downloaded a fresh copy of blender 4.0.1 and the zip file you link and made a clean installation of mpfb there. The problem does not arise when I create a human from scratch and apply the "middleage caucasian male" skin.

This makes me wonder if there are remnants of earlier installations which might confuse blender's python interpreter on your system. To be clear: this is mainly a guess from my part, rather than any hard facts though.

Seeming as you are on linux, it should be relatively easy to test though. What I suggest is the following:

* Disable and remove the mpfb2 addon from within blender. That is, go to the addon panel, find the mpfb addon, expand its panel and click the "remove" button.
* Close blender
* Check that the scripts dir does not contain any traces of mpfb (ie "ls /home/jh/.config/blender/4.0/scripts/addons")
* Start blender again and go to the addons panel
* Make sure blender does not find mpfb if entering "mpfb" in the search box
* Install mpfb again 

Doing the above should not affect your user data, but you might want to make a backup of /home/jh/.config/blender/4.0/scripts just to be sure.

If the problem still persist after a reinstallation, can you set the nodeservice log level to DEBUG, repeat the procedure that causes the crash,  export the nodeservice log file and attach it here?

![image](https://github.com/makehumancommunity/mpfb2/assets/10105480/e4337d97-dd5f-49dd-a61e-3a5f1087518b)

**Comment by HaasJona** [comment]
I just reinstalled the plug-in according to your guide and restarted and now it works fine. (both v1 and v2 skins)

I also noticed I had a parallel installation of Blender 3.6, which I removed. Maybe I got confused between those installations while testing today. In any case, sorry for the confusion. The issue is fixed.
