### ISSUE TITLE
The mixamo mapping logic should look for bones by regexp to cater for different prefix

### ISSUE THREAD

**Issue by fvlasie** [makehumancommunity/mpfb2#180]
The problem is that the FBX imported Mixamo rig is using different bone names than expected.

When snapping a MPFB2 rig to a Mixamo rig an error is produced: "mixamorig:Hips bone not found in source"
Batch renaming the bones from "mixamorig1" to "mixamorig" solved the problem.

Maybe MPFB2 could look for bones by prefix?

**Platform and versions**
 - OS: Mac (x86) Sonoma 14.4.1
 - Blender 4.1
 - https://files2.makehumancommunity.org/releases/mpfb-2.0-a3.zip

**Comment by joepal1976** [comment]
I've pushed a fix now. It will appear in tomorrow's build if you don't want to run from git. 

Maybe you could check if this solves your problem?

**Comment by fvlasie** [comment]
I just tried the nightly build for May 3 and the problem still persists. 🥺

**Comment by joepal1976** [comment]
Ok, I'll need sample files to test with. Can you provide a zip file with the blend that contains the target and an FBX with the animation you try to apply?

**Comment by fvlasie** [comment]
Thank you for your help! This time I tried it, it worked! 
But I am seeing a lot of distortion in the MPFB character's mesh after snapping. Here is the file:
[mankin.blend.zip](https://github.com/makehumancommunity/mpfb2/files/15255628/mankin.blend.zip)

**Comment by joepal1976** [comment]
I haven't had the time to look into this yet, but a thought: Are you using exactly the same char for both the mixamo doll and the target blender rig? If you get distortion, it sounds as if you tried to snap an animation downloaded for a different doll. To avoid distortion, you need to upload a reduced mixamo for exactly the character you want to animate and then download the animation based on that.

**Comment by fvlasie** [comment]
Yes I downloaded an animation from a Mixamo doll. Let me try your method and I will let you know.
